/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueCreateMetadata : The wrapper for the issue creation metadata for a list of projects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueCreateMetadata {
    /// Expand options that include additional project details in the response.
    #[serde(rename = "expand", skip_serializing_if = "Option::is_none")]
    pub expand: Option<String>,
    /// List of projects and their issue creation metadata.
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<models::ProjectIssueCreateMetadata>>,
}

impl IssueCreateMetadata {
    /// The wrapper for the issue creation metadata for a list of projects.
    pub fn new() -> IssueCreateMetadata {
        IssueCreateMetadata {
            expand: None,
            projects: None,
        }
    }
}

