/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectWithDataPolicy : Details about data policies for a project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectWithDataPolicy {
    /// Data policy.
    #[serde(rename = "dataPolicy", skip_serializing_if = "Option::is_none")]
    pub data_policy: Option<Box<models::ProjectDataPolicy>>,
    /// The project ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
}

impl ProjectWithDataPolicy {
    /// Details about data policies for a project.
    pub fn new() -> ProjectWithDataPolicy {
        ProjectWithDataPolicy {
            data_policy: None,
            id: None,
        }
    }
}

