/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequiredMappingByIssueType : The list of required status mappings by issue type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequiredMappingByIssueType {
    /// The ID of the issue type.
    #[serde(rename = "issueTypeId", skip_serializing_if = "Option::is_none")]
    pub issue_type_id: Option<String>,
    /// The status IDs requiring mapping.
    #[serde(rename = "statusIds", skip_serializing_if = "Option::is_none")]
    pub status_ids: Option<Vec<String>>,
}

impl RequiredMappingByIssueType {
    /// The list of required status mappings by issue type.
    pub fn new() -> RequiredMappingByIssueType {
        RequiredMappingByIssueType {
            issue_type_id: None,
            status_ids: None,
        }
    }
}

