/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SanitizedJqlQueries : The sanitized JQL queries for the given account IDs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SanitizedJqlQueries {
    /// The list of sanitized JQL queries.
    #[serde(rename = "queries", skip_serializing_if = "Option::is_none")]
    pub queries: Option<Vec<models::SanitizedJqlQuery>>,
}

impl SanitizedJqlQueries {
    /// The sanitized JQL queries for the given account IDs.
    pub fn new() -> SanitizedJqlQueries {
        SanitizedJqlQueries {
            queries: None,
        }
    }
}

