/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleListWrapperApplicationRole {
    #[serde(rename = "callback", skip_serializing_if = "Option::is_none")]
    pub callback: Option<serde_json::Value>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::ApplicationRole>>,
    #[serde(rename = "max-results", skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i32>,
    #[serde(rename = "pagingCallback", skip_serializing_if = "Option::is_none")]
    pub paging_callback: Option<serde_json::Value>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl SimpleListWrapperApplicationRole {
    pub fn new() -> SimpleListWrapperApplicationRole {
        SimpleListWrapperApplicationRole {
            callback: None,
            items: None,
            max_results: None,
            paging_callback: None,
            size: None,
        }
    }
}

