/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e098eec8c0925855876f3d946f20a4b01cd69e3c
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowTransition : A workflow transition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowTransition {
    /// The transition ID.
    #[serde(rename = "id")]
    pub id: i32,
    /// The transition name.
    #[serde(rename = "name")]
    pub name: String,
}

impl WorkflowTransition {
    /// A workflow transition.
    pub fn new(id: i32, name: String) -> WorkflowTransition {
        WorkflowTransition {
            id,
            name,
        }
    }
}

